#!/bin/bash
echo
echo
echo "#####################################################################################"
echo "The lab command-list:" 
echo "        1) ps   //  only your processes"
echo "        +   a   //  all processes for all users"
echo "        +   x   //  all processes,  without your terminal"
echo "        +   u   //  for ever processes USER-Name and Time"
echo "_____________________________________________________________________________________"
echo "       Indicate the status of the process (STAT)"
echo "        |   R   //  now working"
echo "        |   S   //  expects"
echo "        |   I   //  waiting inpet/output"
echo "        |   D   //  inaction"
echo "        |   Z   //  zoombie-process"
echo "        |   T   //  was stoped"
echo "_____________________________________________________________________________________"
echo "        2) pstree   //  showw you all processes in the tree"
echo "        +  -p   //  output PID all processes"
echo "        +  -c   //  expand all branches"
echo "        +  -u   //  output user-name, who started process"
echo "_____________________________________________________________________________________"
echo "        3) top   //  in real time"
echo "        +   M   //  to sort processes. Amount of memory they use. (%MEM)"
echo "        +   P   //  for sorting processes by their CPU time. (default)"
echo "        +   U   //  for output processes about one user"
echo "        +   i   //  all processes, sleeps too"
